# Generated by Django

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                help_text='Enter phone number with country code (e.g., +255123456789)', 
                max_length=20, 
                unique=True, 
                validators=[django.core.validators.RegexValidator(regex=r'^\\+?1?\\d{9,15}$', message='Phone number must be entered in the format: \'+999999999\'. Up to 15 digits allowed.')]
            ),
        ),
    ]
