# Generated by Django 5.2.10 on 2026-03-25 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'theme_order']},
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature this product in theme display'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Admin approval required for vendor products'),
        ),
        migrations.AddField(
            model_name='product',
            name='theme_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for theme display'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor who owns this product (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
